version: '3.8'

services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file: .env

volumes:
  static_value:
  media_value:
